# pytorch_lightning==2.1.0
tasks:
- task: upmm
  task_kwargs:
    data_path: /import/research_c4dm/jpmg86/embedding_datasets/upmm/
    csv_path: s3://maml-aimcdt/datasets/upmm/upmm_captions.csv
  split: keep
- task: song_describer
  split: val
  root_dir: /import/research_c4dm/jpmg86/song-describer/data/audio
  new_dir: /import/research_c4dm/jpmg86/song-describer/data/clap/npy
- task: musiccaps
  task_kwargs:
    data_path: /import/c4dm-datasets/musiccaps/musiccaps_10s
    csv_path: /import/c4dm-datasets/musiccaps/musiccaps-public.csv
  split: val
  root_dir: /import/c4dm-datasets/musiccaps/musiccaps_10s
  new_dir: /import/research_c4dm/jpmg86/musiccaps/clap_npy/1hz
dataloader_kwargs:
  preextracted_features: true
  truncate_preextracted: 64
  batch_size: 256
  num_workers: 8
return_audio: true
return_text: true
concept: null
target_n_samples: 96000
target_sr: 48000
batch_size: 32
num_workers: 0
preextracted_features: false
truncate_preextracted: 50
root_dir: null
new_dir: null
