base_name: diffgar
s3_output_root: s3://maml-aimcdt/storage/julien/DiffGAR/training_output/
pull_config: s3://maml-aimcdt/storage/julien/DiffGAR/training_configs/config.yaml
training_input:
  # s3_data: s3://maml-aimcdt/datasets/song-describer/data/clap/npy/1hz/
  # s3_data: s3://maml-aimcdt/datasets/song-describer/data/muleproj/npy/1hz/
  s3_data: s3://maml-aimcdt/datasets/GDR-Training/
  # s3_data: s3://maml-aimcdt/datasets/upmm/muleproj/npy/1hz/
  # s3_data: s3://maml-aimcdt/datasets/upmm/muscall/npy/1hz/
  s3_data_type: S3Prefix
  distribution: FullyReplicated
  input_mode: File
estimator:
  image_uri: 427750820708.dkr.ecr.us-east-1.amazonaws.com/diffgar/training:latest
  instance_count: 1
  instance_type: ml.g6e.24xlarge
  role: maml-aimcdt-sagemaker
  hyperparameters:
    entrypoint: train_ldm.py  # don't put leading ./ here
    cfg_fp: s3://maml-aimcdt/storage/julien/DiffGAR/training_configs/config.yaml # this is because the launch script copies the config file to the working directory
  tags:
    - Key: Project
      Value: maml-diffgar
    - Key: Application-Name
      Value: MAML